Cries:
	dba Cry_Nidoran_M
	dba Cry_Nidoran_F
	dba Cry_Ralts
	dba Cry_Kangaskhan
	dba Cry_Charmander
	dba Cry_Grimer
	dba Cry_Voltorb
	dba Cry_Muk
	dba Cry_Oddish
	dba Cry_Raichu
	dba Cry_Nidoqueen
	dba Cry_Diglett
	dba Cry_Seel
	dba Cry_Drowzee
	dba Cry_Pidgey
	dba Cry_Bulbasaur
	dba Cry_Taillow
	dba Cry_Rhydon
	dba Cry_Golem
	dba Cry_Blastoise
	dba Cry_Pidgeotto
	dba Cry_Weedle
	dba Cry_Wurmple
	dba Cry_Ekans
	dba Cry_Swellow
	dba Cry_Clefairy
	dba Cry_Venonat
	dba Cry_Lapras
	dba Cry_Silcoon
	dba Cry_Squirtle
	dba Cry_Surskit
	dba Cry_Growlithe
	dba Cry_Krabby
	dba Cry_Psyduck
	dba Cry_Poochyena
	dba Cry_Vileplume
	dba Cry_Vulpix
	dba Cry_Weepinbell
	dba Cry_Marill
	dba Cry_Spinarak
	dba Cry_Togepi
	dba Cry_Girafarig
	dba Cry_Raikou
	dba Cry_Mareep
	dba Cry_Togetic
	dba Cry_Vigoroth
	dba Cry_Zigzagoon
	dba Cry_Slowking
	dba Cry_Torchic
	dba Cry_Treecko
	dba Cry_Mudkip
	dba Cry_Gligar
	dba Cry_Cleffa
	dba Cry_Slugma
	dba Cry_Ledyba
	dba Cry_Entei
	dba Cry_Wooper
	dba Cry_Mantine
	dba Cry_Blaziken
	dba Cry_Natu
	dba Cry_Teddiursa
	dba Cry_Breloom
	dba Cry_Ampharos
	dba Cry_Magcargo
	dba Cry_Pichu
	dba Cry_Aipom
	dba Cry_Dunsparce
	dba Cry_Donphan
