JohtoFrames: ; used only for BANK(JohtoFrames)

TreeckoFrames:
GrovyleFrames:
SceptileFrames:
TorchicFrames:
CombuskenFrames:
BlazikenFrames:
MudkipFrames:
MarshtompFrames:
SwampertFrames:
ZigzagoonFrames:
LinooneFrames:
VigorothFrames:
SlakingFrames:
LedybaFrames:
LedianFrames:
SpinarakFrames:
AriadosFrames:
CrobatFrames:
ChinchouFrames:
LanturnFrames:
PichuFrames:
CleffaFrames:
IgglybuffFrames:
TogepiFrames:
TogeticFrames:
NatuFrames:
XatuFrames:
MareepFrames:
FlaaffyFrames:
AmpharosFrames:
BellossomFrames:
MarillFrames:
AzumarillFrames:
SudowoodoFrames:
PolitoedFrames:
HoppipFrames:
SkiploomFrames:
JumpluffFrames:
AipomFrames:
ShroomishFrames:
BreloomFrames:
YanmaFrames:
AzurillFrames:
QuagsireFrames:
EspeonFrames:
UmbreonFrames:
MurkrowFrames:
SlowkingFrames:
MisdreavusFrames:
UnownFrames:
WobbuffetFrames:
GirafarigFrames:
PinecoFrames:
ForretressFrames:
DunsparceFrames:
GligarFrames:
SteelixFrames:
SnubbullFrames:
GranbullFrames:
QwilfishFrames:
ScizorFrames:
ShuckleFrames:
HeracrossFrames:
SneaselFrames:
TeddiursaFrames:
UrsaringFrames:
SlugmaFrames:
MagcargoFrames:
SwinubFrames:
PiloswineFrames:
CorsolaFrames:
RemoraidFrames:
OctilleryFrames:
DelibirdFrames:
MantineFrames:
SkarmoryFrames:
HoundourFrames:
HoundoomFrames:
KingdraFrames:
PhanpyFrames:
DonphanFrames:
Porygon2Frames:
StantlerFrames:
SmeargleFrames:
TyrogueFrames:
HitmontopFrames:
SmoochumFrames:
ElekidFrames:
MagbyFrames:
MiltankFrames:
BlisseyFrames:
RaikouFrames:
EnteiFrames:
SuicuneFrames:
LarvitarFrames:
PupitarFrames:
TyranitarFrames:
LugiaFrames:
HoOhFrames:
CelebiFrames:
EggFrames:
