KantoFrames: ; used only for BANK(KantoFrames)

BulbasaurFrames:
IvysaurFrames:
VenusaurFrames:
CharmanderFrames:
CharmeleonFrames:
CharizardFrames:
SquirtleFrames:
WartortleFrames:
BlastoiseFrames:
WurmpleFrames:
SilcoonFrames:
BeautiflyFrames:
WeedleFrames:
CascoonFrames:
DustoxFrames:
PidgeyFrames:
PidgeottoFrames:
PidgeotFrames:
PoochyenaFrames:
MightyenaFrames:
TaillowFrames:
SwellowFrames:
EkansFrames:
ArbokFrames:
PikachuFrames:
RaichuFrames:
SandshrewFrames:
SandslashFrames:
NidoranFFrames:
NidorinaFrames:
NidoqueenFrames:
NidoranMFrames:
NidorinoFrames:
NidokingFrames:
ClefairyFrames:
ClefableFrames:
VulpixFrames:
NinetalesFrames:
JigglypuffFrames:
WigglytuffFrames:
ZubatFrames:
GolbatFrames:
OddishFrames:
GloomFrames:
VileplumeFrames:
SurskitFrames:
MasquerainFrames:
VenonatFrames:
VenomothFrames:
DiglettFrames:
DugtrioFrames:
MeowthFrames:
PersianFrames:
PsyduckFrames:
GolduckFrames:
MankeyFrames:
PrimeapeFrames:
GrowlitheFrames:
ArcanineFrames:
PoliwagFrames:
PoliwhirlFrames:
PoliwrathFrames:
AbraFrames:
KadabraFrames:
AlakazamFrames:
MachopFrames:
MachokeFrames:
MachampFrames:
BellsproutFrames:
WeepinbellFrames:
VictreebelFrames:
TentacoolFrames:
TentacruelFrames:
GeodudeFrames:
GravelerFrames:
GolemFrames:
PonytaFrames:
RapidashFrames:
RaltsFrames:
KirliaFrames:
MagnemiteFrames:
MagnetonFrames:
FarfetchDFrames:
DoduoFrames:
DodrioFrames:
SeelFrames:
DewgongFrames:
GrimerFrames:
MukFrames:
WingullFrames:
PelipperFrames:
GastlyFrames:
HaunterFrames:
GengarFrames:
OnixFrames:
DrowzeeFrames:
HypnoFrames:
KrabbyFrames:
KinglerFrames:
VoltorbFrames:
ElectrodeFrames:
SeedotFrames:
NuzleafFrames:
CuboneFrames:
MarowakFrames:
HitmonleeFrames:
HitmonchanFrames:
LickitungFrames:
KoffingFrames:
WeezingFrames:
RhyhornFrames:
RhydonFrames:
ChanseyFrames:
ShiftryFrames:
KangaskhanFrames:
HorseaFrames:
SeadraFrames:
GoldeenFrames:
SeakingFrames:
StaryuFrames:
StarmieFrames:
MrMimeFrames:
ScytherFrames:
JynxFrames:
ElectabuzzFrames:
MagmarFrames:
PinsirFrames:
TaurosFrames:
MagikarpFrames:
GyaradosFrames:
LaprasFrames:
DittoFrames:
EeveeFrames:
VaporeonFrames:
JolteonFrames:
FlareonFrames:
PorygonFrames:
OmanyteFrames:
OmastarFrames:
KabutoFrames:
KabutopsFrames:
AerodactylFrames:
SnorlaxFrames:
ArticunoFrames:
ZapdosFrames:
MoltresFrames:
DratiniFrames:
DragonairFrames:
DragoniteFrames:
MewtwoFrames:
MewFrames:
