UnownAnimations: ; used only for BANK(UnownAnimations)

UnownAAnimation: endanim "gfx/pokemon/unown_a/anim.asm"
UnownBAnimation: endanim "gfx/pokemon/unown_b/anim.asm"
UnownCAnimation: endanim "gfx/pokemon/unown_c/anim.asm"
UnownDAnimation: endanim "gfx/pokemon/unown_d/anim.asm"
UnownEAnimation: endanim "gfx/pokemon/unown_e/anim.asm"
UnownFAnimation: endanim "gfx/pokemon/unown_f/anim.asm"
UnownGAnimation: endanim "gfx/pokemon/unown_g/anim.asm"
UnownHAnimation: endanim "gfx/pokemon/unown_h/anim.asm"
UnownIAnimation: endanim "gfx/pokemon/unown_i/anim.asm"
UnownJAnimation: endanim "gfx/pokemon/unown_j/anim.asm"
UnownKAnimation: endanim "gfx/pokemon/unown_k/anim.asm"
UnownLAnimation: endanim "gfx/pokemon/unown_l/anim.asm"
UnownMAnimation: endanim "gfx/pokemon/unown_m/anim.asm"
UnownNAnimation: endanim "gfx/pokemon/unown_n/anim.asm"
UnownOAnimation: endanim "gfx/pokemon/unown_o/anim.asm"
UnownPAnimation: endanim "gfx/pokemon/unown_p/anim.asm"
UnownQAnimation: endanim "gfx/pokemon/unown_q/anim.asm"
UnownRAnimation: endanim "gfx/pokemon/unown_r/anim.asm"
UnownSAnimation: endanim "gfx/pokemon/unown_s/anim.asm"
UnownTAnimation: endanim "gfx/pokemon/unown_t/anim.asm"
UnownUAnimation: endanim "gfx/pokemon/unown_u/anim.asm"
UnownVAnimation: endanim "gfx/pokemon/unown_v/anim.asm"
UnownWAnimation: endanim "gfx/pokemon/unown_w/anim.asm"
UnownXAnimation: endanim "gfx/pokemon/unown_x/anim.asm"
UnownYAnimation: endanim "gfx/pokemon/unown_y/anim.asm"
UnownZAnimation: endanim "gfx/pokemon/unown_z/anim.asm"
